blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/florianziesche/focusscore_notiontimer_embed/discussions
    about: Ask questions in Discussions.
